"""add_ticket_and_blocking_reason

Revision ID: de8790e7a269
Revises: 6819167e66ac
Create Date: 2026-06-13 11:39:11.130886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de8790e7a269'
down_revision: Union[str, Sequence[str], None] = '6819167e66ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocking_reasons',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hard_block', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocking_reasons_code'), 'blocking_reasons', ['code'], unique=True)
    op.create_table('tickets',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=8), server_default='CREATE', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('queue_priority', sa.Integer(), server_default='3', nullable=False),
    sa.Column('claimed_by', sa.Uuid(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocking_reason_id', sa.Uuid(), nullable=True),
    sa.Column('moderator_comment', sa.Text(), nullable=True),
    sa.Column('field_reports', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('json_before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_after', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('queue_priority BETWEEN 1 AND 4', name='ck_tickets_queue_priority_range'),
    sa.ForeignKeyConstraint(['blocking_reason_id'], ['blocking_reasons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['claimed_by'], ['moderators.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_category_id'), 'tickets', ['category_id'], unique=False)
    op.create_index(op.f('ix_tickets_claimed_by'), 'tickets', ['claimed_by'], unique=False)
    op.create_index(op.f('ix_tickets_product_id'), 'tickets', ['product_id'], unique=True)
    op.create_index(op.f('ix_tickets_seller_id'), 'tickets', ['seller_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_seller_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_product_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_claimed_by'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_category_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_blocking_reasons_code'), table_name='blocking_reasons')
    op.drop_table('blocking_reasons')
    # ### end Alembic commands ###
