"""add_new_columns_address

Revision ID: 2857cd25e512
Revises: 399862710474
Create Date: 2026-06-13 09:06:07.088318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2857cd25e512'
down_revision: Union[str, Sequence[str], None] = '399862710474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('region', sa.String(length=200), nullable=True))
    op.add_column('addresses', sa.Column('building', sa.String(length=50), nullable=False))
    op.add_column('addresses', sa.Column('apartment', sa.String(length=50), nullable=True))
    op.add_column('addresses', sa.Column('recipient_name', sa.String(length=200), nullable=True))
    op.add_column('addresses', sa.Column('recipient_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'recipient_phone')
    op.drop_column('addresses', 'recipient_name')
    op.drop_column('addresses', 'apartment')
    op.drop_column('addresses', 'building')
    op.drop_column('addresses', 'region')
    # ### end Alembic commands ###
