"""add_new_column_payment_method

Revision ID: e3e14b0a453f
Revises: 2857cd25e512
Create Date: 2026-06-13 09:26:48.772093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3e14b0a453f'
down_revision: Union[str, Sequence[str], None] = '2857cd25e512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_methods', sa.Column('type', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_methods', 'type')
    # ### end Alembic commands ###
