"""add_deleted_blocked_to_product_fix_title_desc

Revision ID: 05df1bb559c2
Revises: 9abefc665eb4
Create Date: 2026-05-09 12:03:35.037545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05df1bb559c2'
down_revision: Union[str, Sequence[str], None] = '9abefc665eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('blocked', sa.Boolean(), nullable=False))
    op.alter_column('products', 'title',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('products', 'blocked')
    op.drop_column('products', 'deleted')
    # ### end Alembic commands ###
