"""fix_product_field_bloking_reason_id_2

Revision ID: 0fb680d90479
Revises: a7594778e584
Create Date: 2026-06-03 15:42:55.347736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fb680d90479'
down_revision: Union[str, Sequence[str], None] = 'a7594778e584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('blocking_reasons_product_id_fkey'), 'blocking_reasons', type_='foreignkey')
    op.drop_column('blocking_reasons', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocking_reasons', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('blocking_reasons_product_id_fkey'), 'blocking_reasons', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
