"""add_token

Revision ID: 1e2febdf5dd1
Revises: c3180b6a0d1e
Create Date: 2026-05-05 19:54:20.267398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e2febdf5dd1'
down_revision: Union[str, Sequence[str], None] = 'c3180b6a0d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('jti', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti')
    )
    op.add_column('categories', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'], ondelete='SET NULL')
    op.add_column('sellers', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('sellers', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('sellers', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('sellers', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('sellers', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('sellers', sa.Column('role', sa.String(length=20), nullable=False))
    op.add_column('sellers', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('sellers', sa.Column('company_name', sa.String(length=255), nullable=False))
    op.add_column('sellers', sa.Column('inn', sa.String(length=12), nullable=False))
    op.create_index(op.f('ix_sellers_email'), 'sellers', ['email'], unique=True)
    op.create_unique_constraint(None, 'sellers', ['inn'])
    op.drop_column('sellers', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sellers', type_='unique')
    op.drop_index(op.f('ix_sellers_email'), table_name='sellers')
    op.drop_column('sellers', 'inn')
    op.drop_column('sellers', 'company_name')
    op.drop_column('sellers', 'is_active')
    op.drop_column('sellers', 'role')
    op.drop_column('sellers', 'password_hash')
    op.drop_column('sellers', 'phone')
    op.drop_column('sellers', 'last_name')
    op.drop_column('sellers', 'first_name')
    op.drop_column('sellers', 'email')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_column('categories', 'parent_id')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
