"""add_reserved_quantity_to_skus

Revision ID: 270bc3b1c63a
Revises: 4ff36b94aa41
Create Date: 2026-05-10 14:31:23.703742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '270bc3b1c63a'
down_revision: Union[str, Sequence[str], None] = '4ff36b94aa41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('reserved_quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skus', 'reserved_quantity')
    # ### end Alembic commands ###
