"""add_processed_events

Revision ID: 36fe289cf329
Revises: 25cad0112e99
Create Date: 2026-06-07 16:16:06.273209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36fe289cf329'
down_revision: Union[str, Sequence[str], None] = '25cad0112e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_moderation_events',
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sender_service', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key', 'sender_service')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_moderation_events')
    # ### end Alembic commands ###
