"""add_hard_blocked_to_product_status

Revision ID: 4ff36b94aa41
Revises: d0c150be8a94
Create Date: 2026-05-10 13:46:33.624801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff36b94aa41'
down_revision: Union[str, Sequence[str], None] = 'd0c150be8a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
