"""add_moderation_tables_and_minor_fixes

Revision ID: aed36c89ad17
Revises: cce523a65e14
Create Date: 2026-06-02 23:18:33.265856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aed36c89ad17'
down_revision: Union[str, Sequence[str], None] = 'cce523a65e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('accepted_quantity', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('blocking_reason_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('moderator_comment', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'products', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'moderator_comment')
    op.drop_column('products', 'blocking_reason_id')
    op.drop_column('products', 'slug')
    op.drop_column('invoice_items', 'accepted_quantity')
    # ### end Alembic commands ###
