"""add_blacklist

Revision ID: cc69eea73a38
Revises: 36fe289cf329
Create Date: 2026-06-10 15:52:00.145423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc69eea73a38'
down_revision: Union[str, Sequence[str], None] = '36fe289cf329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_blacklist',
    sa.Column('jti', sa.Uuid(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.drop_column('refresh_tokens', 'revoked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('revoked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_table('refresh_blacklist')
    # ### end Alembic commands ###
