"""add_stock_quantity_and_article_to_skus

Revision ID: cce523a65e14
Revises: 4169840b9218
Create Date: 2026-05-17 18:33:34.477245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cce523a65e14'
down_revision: Union[str, Sequence[str], None] = '4169840b9218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('stock_quantity', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('skus', sa.Column('article', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skus', 'article')
    op.drop_column('skus', 'stock_quantity')
    # ### end Alembic commands ###
