"""add_cost_price_discount_to_skus

Revision ID: d0c150be8a94
Revises: 05df1bb559c2
Create Date: 2026-05-10 13:25:50.458347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c150be8a94'
down_revision: Union[str, Sequence[str], None] = '05df1bb559c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('cost_price', sa.BigInteger(), nullable=False))
    op.add_column('skus', sa.Column('discount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skus', 'discount')
    op.drop_column('skus', 'cost_price')
    # ### end Alembic commands ###
