"""add_reserve_unreserve_operations

Revision ID: fd48d403b123
Revises: 36fe289cf329
Create Date: 2026-06-08 18:00:42.027795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd48d403b123'
down_revision: Union[str, Sequence[str], None] = '36fe289cf329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserve_operations',
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.create_table('unreserve_operations',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unreserve_operations')
    op.drop_table('reserve_operations')
    # ### end Alembic commands ###
