FROM python:3.13-slim

WORKDIR /app

COPY b2b/requirements.txt b2b/requirements-test.txt .

RUN pip install --no-cache-dir -r requirements.txt -r requirements-test.txt

COPY shared /tmp/shared

RUN pip install --no-cache-dir /tmp/shared

COPY b2b/src /app/src

COPY b2b/migrations /app/migrations

COPY b2b/alembic.ini /app/alembic.ini

CMD ["pytest", "tests/", "-v", "--cov=src", "--cov-report=term"]