FROM python:3.13-slim

WORKDIR /app

COPY b2c/requirements.txt b2c/requirements-test.txt .

RUN pip install --no-cache-dir --index-url https://pypi.org/simple --extra-index-url https://mirror.yandex.ru/pypi/simple/ -r requirements.txt -r requirements-test.txt

COPY shared /tmp/shared

RUN pip install --no-cache-dir /tmp/shared

COPY b2c/src /app/src

COPY b2c/migrations /app/migrations

COPY b2c/alembic.ini /app/alembic.ini

CMD ["pytest", "tests/", "-v", "--cov=src", "--cov-report=term"]